name 'puppet-nabaztag'
version '0.1.0'
license 'Apache 2.0'
summary 'Report processor that notifies your Nabaztag about failed Puppet runs'
project_page 'https://github.com/attachmentgenie/puppet-nabaztag'
