name 'puppet-nabaztag'
version '1.0.0'

author 'Bram Vogelaar <bram@attachmentgenie.com>'
license 'MIT License'
project_page 'https://github.com/attachmentgenie/puppet-nabaztag'
source 'git://github.com/attachmentgenie/puppet-nabaztag.git'
summary 'Report processor that notifies your Nabaztag about failed Puppet runs'
description 'Report processor that notifies your Nabaztag about failed Puppet runs'
dependency 'puppetlabs/stdlib', '>=2.2.1'